"""add role to chat

Revision ID: c1eeb2af1b7c
Revises: 595e2c9b038e
Create Date: 2025-02-15 18:09:18.075286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1eeb2af1b7c'
down_revision: Union[str, None] = '595e2c9b038e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'role')
    # ### end Alembic commands ###
